const state={clients:JSON.parse(localStorage.getItem('rx_clients')||'[]'),reports:JSON.parse(localStorage.getItem('rx_reports')||'[]'),activity:JSON.parse(localStorage.getItem('rx_activity')||'[]')};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const save=()=>{localStorage.setItem('rx_clients',JSON.stringify(state.clients));localStorage.setItem('rx_reports',JSON.stringify(state.reports));localStorage.setItem('rx_activity',JSON.stringify(state.activity));};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function log(text){state.activity.unshift({text,time:new Date().toLocaleString()});state.activity=state.activity.slice(0,50);save();renderActivity()}
function go(view){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+view).classList.add('active-view');$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));const titles={dashboard:'Team Dashboard',clients:'Clients',reports:'Reports',create:'Create Report',activity:'Activity'};$('#pageTitle').textContent=titles[view];if(view==='create')prepareCreate();window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));
function render(){ $('#kpiClients').textContent=state.clients.length;$('#kpiReports').textContent=state.reports.length;$('#kpiPublished').textContent=state.reports.filter(r=>r.status==='Published').length;const today=new Date().toISOString().slice(0,10);$('#kpiToday').textContent=state.reports.filter(r=>r.createdDate===today).length;renderClients();renderReports();renderRecent();renderActivity();populateClients();updatePreview();}
function renderClients(){const box=$('#clientList');if(!state.clients.length){box.innerHTML='<div class="empty large"><div class="empty-icon">＋</div><h3>No clients added</h3><p>Add your first client to start creating reports.</p><button class="primary" id="emptyAddClient">Add Client</button></div>';$('#emptyAddClient').onclick=openModal;return}box.innerHTML=state.clients.map(c=>`<div class="client-card"><span class="client-id">CLIENT ID · ${esc(c.id)}</span><h3>${esc(c.name)}</h3><p>${esc(c.notes||'No notes added')}</p><div><span class="pill green">${state.reports.filter(r=>r.clientId===c.id).length} Reports</span></div></div>`).join('')}
function populateClients(){const s=$('#clientSelect');const current=s.value;s.innerHTML='<option value="">Select client</option>'+state.clients.map(c=>`<option value="${escAttr(c.id)}">${esc(c.name)} — ${esc(c.id)}</option>`).join('');s.value=current}
function renderRecent(){const box=$('#recentReports');const rs=state.reports.slice(0,5);if(!rs.length){box.className='empty';box.innerHTML='No reports yet. Create your first report.';return}box.className='';box.innerHTML=rs.map(r=>`<div class="activity-item"><div><b>${esc(r.headerTitle)}</b><div><small>${esc(r.clientName)} · ${esc(r.reportType)}</small></div></div><span class="pill ${r.status==='Published'?'green':'amber'}">${r.status}</span></div>`).join('')}
function renderReports(){const q=($('#reportSearch')?.value||'').toLowerCase();const f=$('#reportFilter')?.value||'all';const rs=state.reports.filter(r=>(f==='all'||r.status.toLowerCase()===f)&&(r.headerTitle+' '+r.clientName+' '+r.reportType).toLowerCase().includes(q));const tb=$('#reportTable');if(!rs.length){tb.innerHTML='<tr><td colspan="6" class="empty">No reports available.</td></tr>';return}tb.innerHTML=rs.map(r=>`<tr><td><b>${esc(r.headerTitle)}</b><br><small>${esc(r.reportType)}</small></td><td>${esc(r.clientName)}</td><td>${esc(r.period||r.reportDate||'—')}</td><td>${esc(r.location||'—')}</td><td><span class="pill ${r.status==='Published'?'green':'amber'}">${r.status}</span></td><td>${esc(r.createdAt)}</td></tr>`).join('')}
function renderActivity(){const box=$('#activityList');if(!state.activity.length){box.innerHTML='<div class="empty large">No activity yet.</div>';return}box.innerHTML=state.activity.map(a=>`<div class="activity-item"><span>${esc(a.text)}</span><small>${esc(a.time)}</small></div>`).join('')}
function openModal(){$('#modal').classList.add('show');$('#newClientName').focus()}function closeModal(){$('#modal').classList.remove('show');$('#clientForm').reset()}$('#addClientBtn').onclick=openModal;$('#closeModal').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
$('#clientForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#newClientName').value.trim(),id=$('#newClientId').value.trim();if(state.clients.some(c=>c.id.toLowerCase()===id.toLowerCase()))return toast('Client ID already exists.');state.clients.push({name,id,notes:$('#newClientNotes').value.trim()});save();log(`Client created: ${name} (${id})`);closeModal();render();toast('Client created successfully.');go('clients')});
function prepareCreate(){populateClients();if(!$('#reportDate').value)$('#reportDate').value=new Date().toISOString().slice(0,10);updatePreview()}
$('#reportFile').addEventListener('change',e=>$('#fileName').textContent=e.target.files[0]?.name||'No file selected');$('#reportSearch').addEventListener('input',renderReports);$('#reportFilter').addEventListener('change',renderReports);
['headerTitle','headerSubtitle','periodFrom','periodTo','location','preparedBy'].forEach(id=>$('#'+id).addEventListener('input',updatePreview));
function updatePreview(){if(!$('#headerPreview'))return;const title=$('#headerTitle').value||'Your Report Title',sub=$('#headerSubtitle').value||'Subtitle will appear here',from=$('#periodFrom').value,to=$('#periodTo').value,loc=$('#location').value||'—';$('#headerPreview').innerHTML=`<span>REPORT HEADER</span><h2>${esc(title)}</h2><p>${esc(sub)}</p><div><b>Period:</b> ${from||'—'} ${to?'to '+to:''} &nbsp; <b>Location:</b> ${esc(loc)}</div>`}
function collect(status){const c=state.clients.find(x=>x.id===$('#clientSelect').value);if(!c)return null;const file=$('#reportFile').files[0];return {id:crypto.randomUUID(),clientId:c.id,clientName:c.name,reportName:$('#reportName').value.trim(),reportType:$('#reportType').value,reportDate:$('#reportDate').value,headerTitle:$('#headerTitle').value.trim(),headerSubtitle:$('#headerSubtitle').value.trim(),period:($('#periodFrom').value||'')+($('#periodTo').value?' to '+$('#periodTo').value:''),location:$('#location').value.trim(),preparedBy:$('#preparedBy').value.trim(),headerNote:$('#headerNote').value.trim(),fileName:file?.name||'No file attached',status,createdDate:new Date().toISOString().slice(0,10),createdAt:new Date().toLocaleString()}}
$('#saveDraft').onclick=()=>{const r=collect('Draft');if(!r)return toast('Please select a client.');state.reports.unshift(r);save();log(`Report saved as draft: ${r.headerTitle} for ${r.clientName}`);render();toast('Report draft saved.');go('reports')}
$('#reportForm').addEventListener('submit',e=>{e.preventDefault();const r=collect('Published');if(!r)return toast('Please select a client.');if(!$('#reportFile').files[0])return toast('Please upload the report file.');state.reports.unshift(r);save();log(`Report published: ${r.headerTitle} for ${r.clientName}`);toast('Report uploaded and published.');e.target.reset();$('#fileName').textContent='No file selected';render();go('reports')});
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function escAttr(v){return esc(v)}
render();
